/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2023-09-05 18:51:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>World Clock</title>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"css/index.css\">\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar\">\r\n");
      out.write("         <!-- l0go -->\r\n");
      out.write("        <!-- <h1><a href=\"#\"><img src=\"images/logo.png\" alt=\"\"></a>WOrld Clock</h1> -->\r\n");
      out.write("        <h1>World Clock</h1>\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"#home\">Home</a></li>\r\n");
      out.write("            <li><a href=\"#about\">About Us</a></li>\r\n");
      out.write("            <li><a href=\"#contact\">Contact</a></li>\r\n");
      out.write("            <li><a href=\"profile.jsp\">Profile</a></li>\r\n");
      out.write("            <li><span><a href=\"logout\">Logout</a></span></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("<!-- home -->\r\n");
      out.write("    <section id=\"home\">\r\n");
      out.write("\r\n");
      out.write("      <div id=\"clock\">11 Dec 2022 <br>\r\n");
      out.write("        8:10:45</div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"main\">\r\n");
      out.write("            <h1 class=\"headings\">Hii <span>");
      out.print( session.getAttribute("name") );
      out.write("</span>,<br>Welcome to our website<span> World Clock</span><br>Are you interested to look towards<br>the times of different Continents?<br> Then <span>click</span> the below button to continue </h1>\r\n");
      out.write("             \r\n");
      out.write("            <a href=\"allclock.jsp\" target=\"blank\"><button class=\"btn\">\r\n");
      out.write("                Show Time\r\n");
      out.write("            </button></a><br>\r\n");
      out.write("            \r\n");
      out.write("            <a href=\"alaram/alaram.html\" target=\"blank\"><button class=\"btn\">\r\n");
      out.write("                Set Alarm\r\n");
      out.write("            </button></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("<!-- home end -->\r\n");
      out.write("\r\n");
      out.write("<!-- About -->\r\n");
      out.write("    <section id=\"about\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"big_container\">\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("              <h1 class=\"headings\">ABOUT US</h1>\r\n");
      out.write("              <div class=\"bord\"></div>\r\n");
      out.write("      \r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                  <div class=\"prof\">\r\n");
      out.write("                    <!--<img src=\"images/p1.jpeg\" alt=\"\">  -->\r\n");
      out.write("                    <img src=\"images/biku.jpg\" alt=\"\">\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"pname\">Dibya Ranjan Rath</div>\r\n");
      out.write("            \r\n");
      out.write("                    <p>\r\n");
      out.write("                    I am a 3rd year B-Tech student in CSE branch of Silicon Institute Of Technology, Bhubaneswar<br>Sic-20BCSE62 \r\n");
      out.write("                     <!--  Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, -->\r\n");
      out.write("                    </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("      \r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                  <div class=\"prof\">\r\n");
      out.write("                    <img src=\"images/p2.jpeg\" alt=\"\">\r\n");
      out.write("                    <div class=\"pname\">Soumendra Pradhan</div>\r\n");
      out.write("      \r\n");
      out.write("                    <p>\r\n");
      out.write("                      I am a 3rd year B-Tech student in CSE branch of Silicon Institute Of Technology, Bhubaneswar<br>Sic-21BCSL08\r\n");
      out.write("                    </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("      \r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                  <div class=\"prof\">\r\n");
      out.write("                    <img src=\"images/p3.jpeg\" alt=\"\">\r\n");
      out.write("                    <div class=\"pname\">Aditya Prasad</div>\r\n");
      out.write("      \r\n");
      out.write("                    <p>\r\n");
      out.write("                    I am a 3rd year B-tech student in CEN branch of Silicon Institute Of Technology, Bhubaneswar<br>Sic-20BCEF95 \r\n");
      out.write("                    </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("              \r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("<!-- About end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- Contact -->\r\n");
      out.write("    <section id=\"contact\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"big_container\">\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("              <h1 class=\"headings\">Contact Us</h1>\r\n");
      out.write("              <div class=\"bord\"></div>\r\n");
      out.write("      \r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                  <div class=\"prof\">\r\n");
      out.write("                    <a href=\"https://www.google.com/maps/place/Silicon+Institute+of+Technology/@20.3506823,85.8041473,17z/data=!3m1!4b1!4m5!3m4!1s0x3a1908e064769e73:0x9288172f3a98c7a4!8m2!3d20.3506773!4d85.806336\" target=\"blank\">\r\n");
      out.write("                        <img src=\"images/location.jpg\" alt=\"\"></a>\r\n");
      out.write("                    <div class=\"pname\">\r\n");
      out.write("                        Location\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        Silicon College <br>\r\n");
      out.write("                        Bhubaneswar, Khorda-751002\r\n");
      out.write("                        \r\n");
      out.write("                    </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                    <div class=\"prof\">\r\n");
      out.write("                      <a href=\"https://mail.google.com/mail/u/0/#inbox?compose=new\" target=\"blank\"><img src=\"images/mail.png\" alt=\"\"></a>\r\n");
      out.write("                      <div class=\"pname\">Email</div>\r\n");
      out.write("        \r\n");
      out.write("                      <p>\r\n");
      out.write("                        info.college@silicon.ac.in<br>\r\n");
      out.write("                       cse.ajpstudent@silicon.ac.in\r\n");
      out.write("                      </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col\">\r\n");
      out.write("                    <div class=\"prof\">\r\n");
      out.write("                        <a href=\"https://www.truecaller.com/auth/sign-in\" target=\"blank\">\r\n");
      out.write("                      <img src=\"images/call.png\" alt=\"\"> </a>\r\n");
      out.write("                      <div class=\"pname\">Contact number</div> \r\n");
      out.write("        \r\n");
      out.write("                      <p>\r\n");
      out.write("                        (+91)784908XX<br>\r\n");
      out.write("                        (751)132000XX\r\n");
      out.write("                      </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section> \r\n");
      out.write("\r\n");
      out.write("<!--  ...........................................................   -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/home_clock.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
